version: '3'
services:
  tensorboard:
    image: tensorflow/tensorflow:latest
    ports:
      - "6006:6006"
    volumes:
      - /Docker/Docker_Config/Jupyterlab/logs/:/logs  # Mount your TensorFlow logs directory
    command: tensorboard --logdir=/logs --bind_all
    restart: always

