global:
  scrape_interval:     15s # By default, scrape targets every 15 seconds.
  evaluation_interval: 15s # Time evaluation of a certain condition
  external_labels:
    monitor: 'codelab-monitor'
scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9090']
  - job_name: "node_exporter"
    static_configs:
      - targets: ['192.168.0.16:9100'] # Requires the local IP of the server
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['192.168.0.16:8085'] # Requires the local IP of the serve:wqr
