---
services:
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ="Europe/Madrid"
    volumes:
      - /Docker/Docker_Config/Sonarr:/config
      - /Media/Series:/tv #optional
      - /Media/Series:/downloads #optional
    ports:
      - 8989:8989
    restart: unless-stopped
