---
services:
  deluge:
    image: lscr.io/linuxserver/deluge:latest
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - DELUGE_LOGLEVEL=error #optional
    volumes:
      - /Docker/Docker_Config/Deluge_Sonarr/config:/config
      - /Media/Series:/downloads
    ports:
      - 8113:8112
      - 6883:6881
      - 6883:6881/udp
      - 58843:58846 #optional
    restart: unless-stopped
