version: "2.1"
services:
  jellyfin:
    image: ghcr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Madrid
    volumes:
      - /Docker/Docker_Config/Jellyfin/config:/config
      - /Docker/Docker_Config/Jellyfin/cache:/cache
      - /Storage/Media:/media
    ports:
      - 8096:8096
    restart: unless-stopped
