---
services:
  deluge:
    image: lscr.io/linuxserver/deluge:latest
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - DELUGE_LOGLEVEL=error #optional
    volumes:
      - /Docker/Docker_Config/Deluge_Radarr/config:/config
      - /Media/Movies:/downloads
    ports:
      - 8114:8112
      - 6884:6881
      - 6884:6881/udp
      - 58844:58846 #optional
    restart: unless-stopped
