version: '3'
services:
  jupyterlab:
    image: jupyter/datascience-notebook:latest
    ports:
      - "8888:8888"
    volumes:
      - /Docker/Docker_Config/Jupyterlab/notebooks:/home/jovyan/work
    environment:
      - JUPYTER_ENABLE_LAB=yes
    restart: always
