- name: Security patch for a server
  hosts: all
  become: yes
  tasks:
  - name: Copy SHH keys to the remote servers
    ansible.posix.authorized_key:
      user: "{{ ansible_ssh_user }}" # Current user of the desktop
      state: present
      key: "{{ lookup('file', '/home/gabriel/.ssh/id_ed25519.pub') }}"

  - name: Disable PAM
    lineinfile:
      dest: /etc/ssh/sshd_config
      regexp: '^#?\s*UsePAM\s'
      line: 'UsePAM no'
      state: present

  - name: Password sshd set up to NO
    lineinfile:
      dest: /etc/ssh/sshd_config
      regexp: '^#?\s*PasswordAuthentication\s'
      line: 'PasswordAuthentication no'
      state: present

  - name: Restart the sshd service
    ansible.builtin.systemd_service:
      state: restarted
      daemon_reload: true
      name: sshd
