- name: Set up a Gitea server that you can connect to via a VPN
  hosts: all
  become: yes
  tasks:


 # -.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.- #
 #      Security
 # -.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.- #

  - name: Copy SHH keys to the remote servers
    ansible.posix.authorized_key:
      user: "{{ ansible_ssh_user }}" # Current user of the desktop
      state: present
      key: "{{ lookup('file', '/home/gabriel/.ssh/id_ed25519.pub') }}"

  - name: Disable PAM
    lineinfile:
      dest: /etc/ssh/sshd_config
      regexp: '^#?\s*UsePAM\s'
      line: 'UsePAM no'
      state: present

  - name: Password sshd set up to NO
    lineinfile:
      dest: /etc/ssh/sshd_config
      regexp: '^#?\s*PasswordAuthentication\s'
      line: 'PasswordAuthentication no'
      state: present

  - name: Restart the sshd service
    ansible.builtin.systemd_service:
      state: restarted
      daemon_reload: true
      name: sshd


 # -.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.- #
 #      Docker
 # -.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.- #
  - name: Install docker dependencies
    apt:
      name: "{{item}}"
      state: present
      update_cache: yes
    loop:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg-agent
    
  - name: Add  dockers GPG key
    apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg
      state: present

  - name: Add docker repository
    apt_repository:
      repo: deb https://download.docker.com/linux/ubuntu bionic stable
      state: present

  - name: Install docker
    apt:
      name: "{{ item }}"
      state: latest
      update_cache: yes
    loop:
      - docker-ce
      - docker-ce-cli
      - containerd.io


# Installing all of the docker images into the device
  - name: Copy docker compose files
    ansible.builtin.copy:
      src: ./Docker/Docker_Images/{{ item }}
      dest: /Docker/Docker_Images/
    loop:
      - Watchtower
      - Gitea

  - name: Compile all of the docker composes
    command: docker compose -f /Docker/Docker_Images/{{ item }}/docker-compose.yml up -d
    loop:
      - Watchtower
      - Gitea


